apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-migrate
  namespace: incidentguard
  labels:
   app.kubernetes.io/name: backend-migrate
   app.kubernetes.io/part-of: incidentguard
automountServiceAccountToken: false