apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend
  namespace: incidentguard
  labels:
   app.kubernetes.io/name: frontend
   app.kubernetes.io/part-of: incidentguard
automountServiceAccountToken: false