apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres
  namespace: incidentguard
  labels:
   app.kubernetes.io/name: postgres
   app.kubernetes.io/part-of: incidentguard 
automountServiceAccountToken: false