apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: incidentguard
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: incidentguard
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
  template:
    metadata:
      labels:
        app.kubernetes.io/name: postgres
        app.kubernetes.io/part-of: incidentguard
    spec:
      containers:
        - image: postgres:16-alpine@sha256:0fc5c901ec0a3c55ce70b99b040daeb89d5b35b61febbced1b4b24dbc3153ec8
          name: postgres
          ports:
            - name: postgres
              containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-credentials
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          readinessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U \"$POSTGRES_USER\""]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["sh", "-c", "pg_isready -U \"$POSTGRES_USER\""]
            initialDelaySeconds: 30
            periodSeconds: 15
          resources:
            requests: { cpu: 100m, memory: 128Mi }
            limits: { cpu: 500m, memory: 256Mi }
          securityContext:
            allowPrivilegeEscalation: false #bloqueia sudo/setuid
            readOnlyRootFilesystem: true # filesystem do container somente leitura
            capabilities:
              drop: ["ALL"] # zera privilégios de kernel
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-socket
              mountPath: /var/run/postgresql
      securityContext:
        runAsNonRoot: true
        runAsUser: 70 # UID criado na imagem do postgres:16-Alpine (digest da imagem está pinado)
        runAsGroup: 70 # GID criado na imagem do postgres:16-Alpine (digest da imagem está pinado)
        fsGroup: 70
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: postgres-socket
          emptyDir: {}
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

